/**
 * Audit Report & Verification Exporter
 * Exports structured policy audits, line citations, and executive summaries to Markdown or JSON.
 */

export function exportToMarkdown(docTitle, parsedDoc, summaryData, auditResults) {
  const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);
  
  let md = `# MEDICAL BOARD POLICY VERIFIABLE AUDIT REPORT\n`;
  md += `**Document Title:** ${docTitle}\n`;
  md += `**Audit Date:** ${timestamp} UTC\n`;
  md += `**Total Indexed Lines:** ${parsedDoc.metadata.totalLines} | **Word Count:** ${parsedDoc.metadata.wordCount}\n`;
  md += `**Overall Compliance Risk Level:** ${summaryData.stats?.riskLevel || 'Evaluated'}\n\n`;

  md += `---\n\n`;
  md += `## 1. EXECUTIVE SUMMARY & STATUTORY TAKEAWAYS\n\n`;
  md += `${summaryData.overview}\n\n`;

  if (summaryData.keyTakeaways && summaryData.keyTakeaways.length > 0) {
    md += `### Key Verifiable Findings\n\n`;
    summaryData.keyTakeaways.forEach((item) => {
      md += `- **${item.topic}** [Line ${item.citation.startLine}]: ${item.text}\n`;
    });
    md += `\n`;
  }

  md += `---\n\n`;
  md += `## 2. COMPLIANCE AUDIT MATRIX & CITATION TRACE\n\n`;
  md += `| Rule ID | Category | Compliance Status | Rule Requirement | Citation | Findings |\n`;
  md += `|---------|----------|-------------------|------------------|----------|----------|\n`;

  auditResults.forEach((item) => {
    const statusTag = item.status.toUpperCase();
    md += `| \`${item.id}\` | ${item.category} | **${statusTag}** | ${item.ruleRequirement} | Lines ${item.citation.startLine}-${item.citation.endLine} | ${item.findings} |\n`;
  });

  md += `\n---\n\n`;
  md += `## 3. VERBATIM EVIDENCE EXTRACTS\n\n`;

  auditResults.forEach((item) => {
    md += `### [${item.id}] ${item.title}\n`;
    md += `- **Citation:** Lines ${item.citation.startLine} to ${item.citation.endLine}\n`;
    md += `- **Verbatim Excerpt:**\n> "${item.verbatimQuote}"\n\n`;
    md += `- **Remediation Action:** ${item.recommendation}\n\n`;
  });

  md += `---\n*Generated by Medical Board Policy Verifiable Agent (Hackathon Edition)*\n`;

  return md;
}

export function exportToJSON(docTitle, parsedDoc, summaryData, auditResults) {
  const exportPayload = {
    metadata: {
      docTitle,
      timestamp: new Date().toISOString(),
      agentVersion: "2.0-verifiable",
      totalLines: parsedDoc.metadata.totalLines,
      wordCount: parsedDoc.metadata.wordCount,
      riskLevel: summaryData.stats?.riskLevel
    },
    executiveSummary: summaryData,
    complianceAuditMatrix: auditResults,
    indexedLines: parsedDoc.lines.map((l) => ({
      line: l.lineNumber,
      section: l.section,
      text: l.text,
      tags: l.tags
    }))
  };

  return JSON.stringify(exportPayload, null, 2);
}

export function downloadFile(content, fileName, contentType) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
